### ISSUE TITLE
Float task calculation results in a ZeroDivisionError error

### ISSUE THREAD

**Issue by ccostino** [18F/tock#656]
When some folks access their timecards they may receive a 500 error, and it appears to be caused by a `ZeroDivisionError` exception being thrown (the stack trace is a bit jumbled with other request info but the relevant info is there):

```
INFO | ERROR:django.request:Internal Server Error: /reporting_period/2017-08-13/
INFO | return handler(request, *args, **kwargs)
INFO | File "/home/vcap/deps/0/python/lib/python3.5/site-packages/django/views/generic/edit.py", line 236, in get
INFO | File "/home/vcap/deps/0/python/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
INFO | File "/home/vcap/deps/0/python/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
INFO | File "/home/vcap/app/tock/hours/float.py", line 66, in get_tasks
INFO | File "/home/vcap/app/tock/hours/float.py", line 51, in float_tasks_for_view
INFO | response = wrapped_callback(request, *callback_args, **callback_kwargs)
INFO | tasks_to_hours = all_task_hours / work_hours
INFO | File "/home/vcap/deps/0/python/lib/python3.5/site-packages/django/views/generic/edit.py", line 174, in get
INFO | File "/home/vcap/deps/0/python/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
INFO | File "/home/vcap/deps/0/python/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
INFO | Traceback (most recent call last):
INFO | response = self._get_response(request)
INFO | work_hours=work_hours
INFO | ZeroDivisionError: float division by zero
```

Related to this, the tests around this functionality are grouped together in one or two tests, so they should be teased apart to better exercise and validate the methods and calculations.  Then we can add a test for this specific case and work out an appropriate fix for the division error.

/cc @mtorres253, as this directly affects you!

**Comment by ccostino** [comment]
From @mtorres253:

>I still get 500 errors when I try to access timecards from August 6, 2017 to August 12, 2017 and from August 13, 2017 to August 19, 2017.  I am able to access the timesheet for this week [August 21, 2017]

If there's anything else you'd like to add, please feel free to do so!

**Comment by ccostino** [comment]
After conversing with a few more folks it seems to be the issue is caused when a person is out of the office for an entire reporting period, and therefore a full timecard.  This gets recorded in Float (anything more than 3 days out), so the number of "work hours" that comes back is 0, thus resulting in a divide by zero calculation.

After chatting with @annalee about this we both agreed that calculations with Float data should not continue if the amount of work hours is 0, which is taken care of in PR #657.
